### ISSUE TITLE
Can't remove fullscreen widget

### ISSUE THREAD

**Issue by k1tt3hk4t** [balthamos/geektool-3#11]
A widget I accidentally set to fullscreen won't let me disable it so I can continue using nerdtool, so I'm forced to not use it. Is there a way to fix this?

**Comment by balthamos** [comment]
What do you mean by "won't let me disable it". Are you talking about the fullscreen mode, or the widget itself? Are you able to delete the widget?

**Comment by InspectorJavert** [comment]
Hey, I don't know how else to contact you so I'm going through this. Message me through Skype when you can.

**Comment by balthamos** [comment]
Could you explain the issue you are having here? That would be more beneficial to others should they be encountering the same issue.

**Comment by EpochDigitalis** [comment]
k
On Apr 17, 2016 2:58 PM, InspectorJavert <notifications@github.com> wrote:Hey, I don't know how else to contact you so I'm going through this. Message me through Skype when you can.
