### ISSUE TITLE
Safari can't connect to download server

### ISSUE THREAD

**Issue by GingkathFox** [balthamos/geektool-3#13]
All in the title. Safari says it "Safari can’t open the page “https://cloud.github.com/downloads/balthamos/geektool-3/nerdtool-0.8.1.zip” because Safari can’t find the server “cloud.github.com”."

**Comment by balthamos** [comment]
Where are you finding that link? At the following page:

https://github.com/balthamos/geektool-3/releases

I find the link:

https://github.com/balthamos/geektool-3/archive/v0.8.1.zip

Which ends up resolving to:

https://codeload.github.com/balthamos/geektool-3/zip/v0.8.1

**Comment by GingkathFox** [comment]
@balthamos I went to the website. Ill try your link.

**Comment by GingkathFox** [comment]
Huh, your link works. maybe the site dl link is broken?

**Comment by balthamos** [comment]
Ah, you were talking about the website. Yes, the link was broken, thanks for bringing it to attention. It should be fixed now.
