### ISSUE TITLE
Run issues

### ISSUE THREAD

**Issue by GingkathFox** [balthamos/geektool-3#14]
How do I run NerdTool? When I download it, it only gives me the folder.
EDIT: I want to use the Quartz feature to run a visualizer made from [this](https://medium.com/@PatsyTy/geektool-nerdtool-audiobars-theme-showcase-and-tutorial-fd7af687cfbc) tut.

**Comment by balthamos** [comment]
You probably downloaded the source code.

It looks like a long time ago, GitHub changed how their release system worked. Apparently, NerdTool never migrated to the new system, so those release binaries were lost, and the links to them became broken. This is also why you had issues with the download link working properly from the website in #13.

At any rate, I re-uploaded the release under the new system, so they should be accessible now. You can find the download links for both the release and the source at the following page: https://github.com/balthamos/geektool-3/releases/tag/v0.8.1
