### ISSUE TITLE
Can not work with Mocp

### ISSUE THREAD

**Issue by chinanoahli** [balthamos/geektool-3#9]
I wanted to add `mocp -i` as a script, but it does not show anything

**Comment by balthamos** [comment]
This is probably some pathing issue. You should be able to resolve the issue by specifying the absolute path to mocp.

![screen shot 2015-06-04 at 7 25 28 pm](https://cloud.githubusercontent.com/assets/38643/7997267/b107887e-0aef-11e5-8b27-2b249abad169.png)

**Comment by chinanoahli** [comment]
Thank you for the suggestion!
